version: "3"

services:
  app:
    restart: always
    build: .
    ports:
      - "6700:6700"
    environment:
      APP_ENV: production

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=fastack_user
      - POSTGRES_PASSWORD=fastack_pass
      - POSTGRES_DB=fastack_db
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - 5888:5432

volumes:
  db-data:
